apiVersion: apps/v1
kind: Deployment
metadata:
    name: image-webhook
    labels:
        app: image-webhook
spec:
    replicas: 1
    selector:
        matchLabels:
            app: image-webhook
    template:
        metadata:
            name: image-webhook
            labels:
                app: image-webhook
        spec:
            containers:
                - name: image-webhook-pod
                  image: IMAGE
                  imagePullPolicy: IfNotPresent