apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-daemon
    namespace: registry-system
    labels:
        name: docker-daemon
spec:
    replicas: 1
    selector:
      matchLabels:
        app: docker-daemon
    template:
        metadata:
            labels:
                app: docker-daemon
        spec:
            containers:
                - name: dind-daemon
                  image: docker:19.03.0-beta5-dind
                  imagePullPolicy: IfNotPresent
                  securityContext: 
                    privileged: true 
                  volumeMounts:
                    - name: docker-graph-storage
                      mountPath: /var/lib/docker
            volumes:
                - name: docker-graph-storage
                  emptyDir: {}