apiVersion: v1
kind: Service
metadata:
    name: image-webhook-svc
    labels:
        app: image-webhook
spec:
    ports:
        - port: 443
          targetPort: 8443
    selector:
        app: image-webhook