apiVersion: v1
kind: ConfigMap
metadata:
  name: image-validation-webhook-whitelist
  namespace: registry-system
data:
  whitelist-image.json: |-
    ["image-validation-webhook"]
  whitelist-namespace.json: |-
    ["registry-system"]