apiVersion: v1
kind: ConfigMap
metadata:
  name: image-validation-webhook-whitelist
  namespace: registry-system
data:
  whitelist-images: |-
    docker.io/alpine:latest
    hyperregistry.172.22.11.8.nip.io/library/docker.io/library/alpine:3.3
  whitelist-namespaces: |-
