name: image-validating-webhook
on:
  push:
    branches:
      - main
    tags:
      - v*
      - dev-cosign
  pull_request:
jobs:
  test_crd:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: crd test
        run: make test-crd
  test_gen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          go-version: 1.17
      - name: gen test
        run: make test-gen
  test_verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: verify test
        run: make test-verify
  test_unit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: unit test
        run: make test-unit
  test_lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -v -E gofmt -E golint -E gocyclo -E misspell --timeout 1h0m0s
  deploy-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test_gen, test_verify, test_unit, test_lint, test_crd]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker login -u=tmaxcloudck -p=${{ secrets.DOCKER_HUB_PASSWORD }}

          REPO=tmaxcloudck/image-validation-webhook
          IMG=${REPO}:${GITHUB_REF#refs/tags/}
          docker build . -t ${IMG}
          docker tag ${IMG} ${REPO}:latest
          docker push ${IMG}
          docker push ${REPO}:latest
